# -*- coding: utf-8 -*-
"""Assignment_Joseph_AIBD/001/027

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Yffe6gEcsNJNBNT3Z79HI1cxhh3HdjEK
"""

#Declaring the variables
Name = "Joseph"
Age = 22
State_of_residence = "Kenya"
Favorite_ai_tool = "Gemini"

#Output
print(f"Name: {Name}")
print(f"Age: {Age}")
print(f"State of Residence: {State_of_residence}")
print(f"Favorite AI Tool: {Favorite_ai_tool}")

#Output Option 2
print("--- Using String Concatenation ---")
print("Name: " + Name)
print("Age: " + str(Age)) # Convert age to string
print("State of Residence: " + State_of_residence)
print("Favorite AI Tool: " + Favorite_ai_tool)

"""## Variables with Different Data Types"""

print ("Assignment 2")

# String variable
String_var = "Hello World !!!"

# Integer variable
Integer_var = 12345

# Float variable
Float_var = 1.2345

# Boolean variable
Boolean_var = True

# List of 5 AI tools
List_var = ["TensorFlow", "PyTorch", "Scikit-learn", "Keras", "Hugging Face"]

# Tuple variable
Tuple_var = (10, 20, 30, 40, 50)

# Dictionary variable
Dictionary_var = {"tool1": "TensorFlow", "tool2": "PyTorch", "version": 2.0}


print("String:" + String_var)
print("Integer:" + str(Integer_var))
print("Float:"+ str(Float_var))
print("Boolean:" + str(Boolean_var))
print("List:" + str(List_var))
print("Tuple:" + str(Tuple_var))
print(f"Dictionary: {Dictionary_var}")

# Original string
print(f"Original String: {String_var}")

# Uppercase
uppercase_string = String_var.upper()
print(f"Uppercase: {uppercase_string}")

# Lowercase
lowercase_string = String_var.lower()
print(f"Lowercase: {lowercase_string}")

# Slicing :From index 6 to 11 ( "World")
sliced_string = String_var[6:11]
print(f"Sliced String (index 6 to 11): {sliced_string}")

# Slicing: From the beginning to index 5 ("Hello")
sliced_string_start = String_var[:5]
print(f"Sliced String (beginning to index 5): {sliced_string_start}")

# Slicing: From index 6 to the end ("World !!!")
sliced_string_end = String_var[6:]
print(f"Sliced String (index 6 to end): {sliced_string_end}")

# String with leading and trailing whitespace
whitespace_string = "   Python Programming   "
print(f"Original String with Whitespace: '{whitespace_string}'")

# Stripped string
stripped_string = whitespace_string.strip()
print(f"Stripped String: '{stripped_string}'")

# Concatenation
string_part1 = "AREA AI"
string_part2 = " is helpful!"
concatenated_string = string_part1 + string_part2
print(f"Concatenated String: {concatenated_string}")

# Concatenation using f-strings
concatenated_fstring = f"{String_var} I love {string_part1}."
print(f"Concatenated with f-string: {concatenated_fstring}")